### ISSUE TITLE
Refactor idea: put everything internal in an `_incydr` package

### ISSUE THREAD

**Issue by unparalleled-js** [code42/incydr_python#50]
Rather than having N number of internal modules, you can put everything in an `_incdyr` package and then require less `_` prefixes throughout. This is common in other Python libs, such as `pytest`.

Like here: https://github.com/pytest-dev/pytest/tree/main/src

Both packages are registered, but only one is public.

Just an idea!

**Comment by tora-kozic** [comment]
I like that idea, thanks for the tip!  We'll have to do a refactor before the official release
